1602489600086
1602576009746
1602662400104
1602668043330
1602748809391
1602835200088
1602921600077
1603008000065
1603094409263
1603180800108
1603267200074
1603353600069
1603440000092
1603526400087
1603612800067
1603699200072
1603785600091
1603872000089
1603958400088
1604044800073
1604047228977
1604047418293
1604056432278
1604131200094
1604217600068
1604304000100
1604390400104
1604476800069
1604563200106
1604649600072
1604736000105
1604822400112
1604908800086
1604995200068
1605081600072
1605168000087
1605254400091
1605340800082
1605427200111
1605513600109
1605600000104
1605686400072
1605772800110
Traceback (most recent call last):
  File "/home/pi/Documents/Github/cocoa-getinfo/webupdate_notify.py", line 85, in <module>

    cocoa_analysis.main_process()
  File "/home/pi/Documents/Github/cocoa-getinfo/cocoa_analysis.py", line 23, in main_process

    cocoa_wordsearch_datapush.search_and_push(1)
  File "/home/pi/Documents/Github/cocoa-getinfo/sub_sys/cocoa_wordsearch_datapush.py", line 104, in search_and_push

    found2 = match2[0]
IndexError: list index out of range

1605786831443
Traceback (most recent call last):
  File "/home/pi/Documents/Github/cocoa-getinfo/webupdate_notify.py", line 85, in <module>

    cocoa_analysis.main_process()
  File "/home/pi/Documents/Github/cocoa-getinfo/cocoa_analysis.py", line 23, in main_process
    cocoa_wordsearch_datapush.search_and_push(1)
  File "/home/pi/Documents/Github/cocoa-getinfo/sub_sys/cocoa_wordsearch_datapush.py", line 104, in search_and_push
    found2 = match2[0]
IndexError: list index out of range

1605859209859
1605945600112
1606032000105
1606118400071
1606204810020
Traceback (most recent call last):
  File "/home/pi/Documents/Github/cocoa-getinfo/webupdate_notify.py", line 85, in <module>

    cocoa_analysis.main_process()
  File "/home/pi/Documents/Github/cocoa-getinfo/cocoa_analysis.py", line 23, in main_process

    cocoa_wordsearch_datapush.search_and_push(1)

  File "/home/pi/Documents/Github/cocoa-getinfo/sub_sys/cocoa_wordsearch_datapush.py", line 211, in search_and_push

    f.writelines(dx1)
TypeError: 'int' object is not iterable

1606205211256
Traceback (most recent call last):
  File "/home/pi/Documents/Github/cocoa-getinfo/webupdate_notify.py", line 85, in <module>

    cocoa_analysis.main_process()
  File "/home/pi/Documents/Github/cocoa-getinfo/cocoa_analysis.py", line 23, in main_process
    cocoa_wordsearch_datapush.search_and_push(1)
  File "/home/pi/Documents/Github/cocoa-getinfo/sub_sys/cocoa_wordsearch_datapush.py", line 211, in search_and_push

    f.writelines(dx1)
TypeError: 'int' object is not iterable

1606209107949
Traceback (most recent call last):
  File "/home/pi/Documents/Github/cocoa-getinfo/webupdate_notify.py", line 85, in <module>

    cocoa_analysis.main_process()
  File "/home/pi/Documents/Github/cocoa-getinfo/cocoa_analysis.py", line 23, in main_process
    cocoa_wordsearch_datapush.search_and_push(1)
  File "/home/pi/Documents/Github/cocoa-getinfo/sub_sys/cocoa_wordsearch_datapush.py", line 169, in search_and_push

    dx1 = ffound - yy1
TypeError: unsupported operand type(s) for -: 'int' and 'str'

1606209289690
Traceback (most recent call last):
  File "/home/pi/Documents/Github/cocoa-getinfo/webupdate_notify.py", line 85, in <module>
    cocoa_analysis.main_process()
  File "/home/pi/Documents/Github/cocoa-getinfo/cocoa_analysis.py", line 23, in main_process

    cocoa_wordsearch_datapush.search_and_push(1)
  File "/home/pi/Documents/Github/cocoa-getinfo/sub_sys/cocoa_wordsearch_datapush.py", line 213, in search_and_push

    f.writelines(dx1)
TypeError: 'int' object is not iterable

1606209891500
Traceback (most recent call last):
  File "/home/pi/Documents/Github/cocoa-getinfo/webupdate_notify.py", line 85, in <module>

    cocoa_analysis.main_process()
  File "/home/pi/Documents/Github/cocoa-getinfo/cocoa_analysis.py", line 23, in main_process
    cocoa_wordsearch_datapush.search_and_push(1)
  File "/home/pi/Documents/Github/cocoa-getinfo/sub_sys/cocoa_wordsearch_datapush.py", line 215, in search_and_push

    f.writelines(dx1)
TypeError: 'int' object is not iterable

1606210421674
Traceback (most recent call last):
  File "/home/pi/Documents/Github/cocoa-getinfo/webupdate_notify.py", line 85, in <module>

    cocoa_analysis.main_process()
  File "/home/pi/Documents/Github/cocoa-getinfo/cocoa_analysis.py", line 23, in main_process
    cocoa_wordsearch_datapush.search_and_push(1)
  File "/home/pi/Documents/Github/cocoa-getinfo/sub_sys/cocoa_wordsearch_datapush.py", line 171, in search_and_push
    dx1 = ffound - int(first_line)
NameError: name 'first_line' is not defined

1606210566093
1606210985985
1606291200079
1606377600090
1606464000101
1606550400091
1606636800082
1606723200084
1606809600098
1606896000081
1606982400891
1606984053592
1607068800077
1607155200102
1607241600076
1607328000077
1607342635284
1607414400073
1607500808523
1607587200115
1607673600081
1607760000081
1607846400080
1607932800082
Traceback (most recent call last):
  File "/home/pi/Documents/Github/cocoa-getinfo/webupdate_notify.py", line 85, in <module>

    cocoa_analysis.main_process()
  File "/home/pi/Documents/Github/cocoa-getinfo/cocoa_analysis.py", line 23, in main_process
    cocoa_wordsearch_datapush.search_and_push(1)
  File "/home/pi/Documents/Github/cocoa-getinfo/sub_sys/cocoa_wordsearch_datapush.py", line 121, in search_and_push

    if found == 'N/A' and found2 == 'N/A':  # 追加処理のみ更新無
UnboundLocalError: local variable 'found' referenced before assignment

1608019200121
1608105600100
Traceback (most recent call last):
  File "/home/pi/Documents/Github/cocoa-getinfo/webupdate_notify.py", line 85, in <module>

    cocoa_analysis.main_process()
  File "/home/pi/Documents/Github/cocoa-getinfo/cocoa_analysis.py", line 23, in main_process
    cocoa_wordsearch_datapush.search_and_push(1)
  File "/home/pi/Documents/Github/cocoa-getinfo/sub_sys/cocoa_wordsearch_datapush.py", line 121, in search_and_push
    if found == 'N/A' and found2 == 'N/A':  # 追加処理のみ更新無
UnboundLocalError: local variable 'found' referenced before assignment

1608112993765
Traceback (most recent call last):
  File "/home/pi/Documents/Github/cocoa-getinfo/webupdate_notify.py", line 85, in <module>

    cocoa_analysis.main_process()
  File "/home/pi/Documents/Github/cocoa-getinfo/cocoa_analysis.py", line 23, in main_process
    cocoa_wordsearch_datapush.search_and_push(1)
  File "/home/pi/Documents/Github/cocoa-getinfo/sub_sys/cocoa_wordsearch_datapush.py", line 121, in search_and_push
    if found == 'N/A' and found2 == 'N/A':  # 追加処理のみ更新無

UnboundLocalError: local variable 'found' referenced before assignment

Traceback (most recent call last):
  File "/home/pi/Documents/Github/cocoa-getinfo/webupdate_notify.py", line 85, in <module>
    cocoa_analysis.main_process()
  File "/home/pi/Documents/Github/cocoa-getinfo/cocoa_analysis.py", line 23, in main_process
    cocoa_wordsearch_datapush.search_and_push(1)
  File "/home/pi/Documents/Github/cocoa-getinfo/sub_sys/cocoa_wordsearch_datapush.py", line 121, in search_and_push
    if found == 'N/A' and found2 == 'N/A':  # 追加処理のみ更新無
UnboundLocalError: local variable 'found' referenced before assignment

Traceback (most recent call last):
  File "/home/pi/Documents/Github/cocoa-getinfo/webupdate_notify.py", line 85, in <module>
    cocoa_analysis.main_process()
  File "/home/pi/Documents/Github/cocoa-getinfo/cocoa_analysis.py", line 23, in main_process

    cocoa_wordsearch_datapush.search_and_push(1)
  File "/home/pi/Documents/Github/cocoa-getinfo/sub_sys/cocoa_wordsearch_datapush.py", line 121, in search_and_push
    if found == 'N/A' and found2 == 'N/A':  # 追加処理のみ更新無
UnboundLocalError: local variable 'found' referenced before assignment

Traceback (most recent call last):
  File "/home/pi/Documents/Github/cocoa-getinfo/webupdate_notify.py", line 85, in <module>

    cocoa_analysis.main_process()
  File "/home/pi/Documents/Github/cocoa-getinfo/cocoa_analysis.py", line 23, in main_process
    cocoa_wordsearch_datapush.search_and_push(1)
  File "/home/pi/Documents/Github/cocoa-getinfo/sub_sys/cocoa_wordsearch_datapush.py", line 121, in search_and_push
    if found == 'N/A' and found2 == 'N/A':  # 追加処理のみ更新無
UnboundLocalError: local variable 'found' referenced before assignment

Traceback (most recent call last):
  File "/home/pi/Documents/Github/cocoa-getinfo/webupdate_notify.py", line 85, in <module>

    cocoa_analysis.main_process()
  File "/home/pi/Documents/Github/cocoa-getinfo/cocoa_analysis.py", line 23, in main_process
    cocoa_wordsearch_datapush.search_and_push(1)
  File "/home/pi/Documents/Github/cocoa-getinfo/sub_sys/cocoa_wordsearch_datapush.py", line 121, in search_and_push
    if found == 'N/A' and found2 == 'N/A':  # 追加処理のみ更新無
UnboundLocalError: local variable 'found' referenced before assignment

Traceback (most recent call last):
  File "/home/pi/Documents/Github/cocoa-getinfo/webupdate_notify.py", line 85, in <module>

    cocoa_analysis.main_process()
  File "/home/pi/Documents/Github/cocoa-getinfo/cocoa_analysis.py", line 20, in main_process
    cocoa_pyocr.py_ocr()
  File "/home/pi/Documents/Github/cocoa-getinfo/sub_sys/cocoa_pyocr.py", line 37, in py_ocr
    img = img.convert('RGB')
UnboundLocalError: local variable 'img' referenced before assignment

1608116891450
1608192000085
1608278400098
1608364800111
1608451200094
1608537600074
